# Generated by Django 3.2.9 on 2022-01-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_women_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Famous women', 'verbose_name_plural': 'Famous women'},
        ),
    ]
