# Generated by Django 5.0.4 on 2024-05-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_women_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Women', 'verbose_name_plural': 'Women'},
        ),
    ]
