# Generated by Django 3.2.9 on 2022-01-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_auto_20220122_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name': 'Famous women', 'verbose_name_plural': 'Famous women'},
        ),
    ]
